server:
  port: 9090
eureka:
  instance:
    hostname: userservice
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://192.168.99.100:8761/eureka/
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: admin
  jpa:
    generate-ddl: true
    show-sql: true
  cloud:
    config:
      uri: http://192.168.99.100:8888
      fail-fast: true